# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuesAns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourans', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuesAns.Question')),
            ],
        ),
    ]
